name: d3
version: 0.1.0
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: Data Driven Documents
homepage: https://github.com/rwl/d3.dart
dev_dependencies:
  browser: any
  quiver: any
  test: any
