name: d3
version: 0.0.2
description: Data Driven Documents
author: Richard Lincoln <r.w.lincoln@gmail.com>
homepage: https://github.com/rwl/d3.dart
environment:
  sdk: '>=1.13.0-dev.7'
dependencies:
  intl: any
  js: ^0.6.0-beta
  browser: any
dev_dependencies:
  unittest: any
